"""Recurring-invoice payment insight agent - ported from teammate
feature-annapoorna's branch, extended with a staff-vs-resident perspective
(her version always wrote resident-facing "your payments..." text, even
when called for staff's portfolio-wide view with no lease_id).

Risk classification and the insight text are generated by a local Ollama
LLM from aggregated, PII-free billing facts (counts/ratios/days, no
names/emails). If Ollama is unavailable, a deterministic rule-based
fallback keeps the feature working so the endpoint never hard-fails.
"""

import logging
from dataclasses import dataclass
from decimal import Decimal

from app.ai import ollama_client

logger = logging.getLogger(__name__)

RISK_LEVELS = ("low", "medium", "high")

_RESIDENT_SYSTEM_PROMPT = (
    "You are a billing analyst for a residential property management app. "
    "You are given aggregated, anonymized invoice statistics for one resident's "
    "account. Respond with ONLY a JSON object of the form "
    '{"risk_level": "low|medium|high", "insight": "<one or two short sentences>"}. '
    "Use exactly lowercase risk_level values: low, medium, or high; never use synonyms. "
    "Use the currency and amounts exactly as provided and do not invent or convert figures. "
    "risk_level must reflect how likely the resident is to pay late again. "
    "The insight must be a friendly, concrete, resident-facing tip grounded only "
    "in the given numbers — never invent figures that were not provided. "
    "Address the resident directly as \"you/your\"."
)

_STAFF_SYSTEM_PROMPT = (
    "You are a billing analyst for a residential property management app, "
    "reporting to the property management staff/operations team. You are given "
    "aggregated, anonymized invoice statistics across the ENTIRE property "
    "portfolio (every resident's invoices combined, not one individual). "
    "Respond with ONLY a JSON object of the form "
    '{"risk_level": "low|medium|high", "insight": "<one or two short sentences>"}. '
    "Use exactly lowercase risk_level values: low, medium, or high; never use synonyms. "
    "Use the currency and amounts exactly as provided and do not invent or convert figures. "
    "risk_level must reflect how much collections risk the portfolio currently carries. "
    "The insight must be a concise, operational recommendation for staff (e.g. "
    "which accounts to follow up on, whether to send reminders) grounded only in "
    "the given numbers — never invent figures that were not provided, and never "
    "address a single resident directly (\"you/your\"); write about the "
    "portfolio/residents collectively."
)


@dataclass(frozen=True)
class InvoiceInsightResult:
    risk_level: str
    late_payment_count: int
    total_invoices_considered: int
    average_days_late: float
    overdue_count: int
    overdue_amount: Decimal
    insight: str


@dataclass(frozen=True)
class _BillingFacts:
    total: int
    late_payment_count: int
    average_days_late: float
    overdue_count: int
    overdue_amount: Decimal


def _aggregate_facts(invoices) -> _BillingFacts:
    """Pure arithmetic over the invoice rows; no judgment is made here."""
    total = len(invoices)
    late_days = []
    overdue_count = 0
    overdue_amount = Decimal("0")

    for invoice in invoices:
        if invoice.payment_status == "overdue":
            overdue_count += 1
            overdue_amount += Decimal(invoice.amount)
        elif invoice.payment_status == "paid" and invoice.paid_at is not None:
            days_late = (invoice.paid_at.date() - invoice.due_date).days
            if days_late > 0:
                late_days.append(days_late)

    average_days_late = round(sum(late_days) / len(late_days), 1) if late_days else 0.0
    return _BillingFacts(
        total=total,
        late_payment_count=len(late_days) + overdue_count,
        average_days_late=average_days_late,
        overdue_count=overdue_count,
        overdue_amount=overdue_amount,
    )


def generate_ai_insight(invoices, for_staff: bool = False) -> InvoiceInsightResult:
    """Classifies payment risk and writes the insight using a local Ollama
    model. `for_staff` picks the portfolio-wide staff perspective instead of
    the default single-resident one (see the two system prompts above)."""
    facts = _aggregate_facts(invoices)

    if facts.total == 0:
        no_history = "No billing history across the portfolio yet." if for_staff else "No billing history yet."
        return InvoiceInsightResult("low", 0, 0, 0.0, 0, Decimal("0"), no_history)

    prompt = (
        f"total_invoices={facts.total}\n"
        f"late_or_overdue_payment_count={facts.late_payment_count}\n"
        f"average_days_late_when_late={facts.average_days_late}\n"
        f"currently_overdue_count={facts.overdue_count}\n"
        f"currently_overdue_amount={facts.overdue_amount}\n"
    )

    system_prompt = _STAFF_SYSTEM_PROMPT if for_staff else _RESIDENT_SYSTEM_PROMPT

    try:
        result = ollama_client.generate_json(prompt, system=system_prompt)
        risk_level = _normalize_risk_level(result.get("risk_level"))
        insight = str(result.get("insight", "")).strip()
        if risk_level not in RISK_LEVELS or not insight:
            raise ValueError(f"Model returned an unusable response: {result!r}")
    except Exception as exc:  # noqa: BLE001 - any LLM/network failure falls back safely
        logger.warning("Falling back to rule-based invoice insight: %s", exc)
        risk_level, insight = _fallback_rule_based(facts, for_staff)

    return InvoiceInsightResult(
        risk_level=risk_level,
        late_payment_count=facts.late_payment_count,
        total_invoices_considered=facts.total,
        average_days_late=facts.average_days_late,
        overdue_count=facts.overdue_count,
        overdue_amount=facts.overdue_amount,
        insight=insight,
    )


def _normalize_risk_level(value) -> str:
    normalized = str(value or "").strip().lower()
    aliases = {
        "minimal": "low",
        "safe": "low",
        "moderate": "medium",
        "medium risk": "medium",
        "elevated": "high",
        "high risk": "high",
    }
    return aliases.get(normalized, normalized)


def _fallback_rule_based(facts: _BillingFacts, for_staff: bool = False) -> tuple[str, str]:
    ratio = facts.late_payment_count / facts.total

    if for_staff:
        if ratio == 0:
            risk_level = "low"
            message = "All residents across the portfolio have been paying on time."
        elif ratio <= 0.34:
            risk_level = "medium"
            message = (
                f"{facts.late_payment_count} of the last {facts.total} invoices across the portfolio "
                f"were paid late (avg {facts.average_days_late} days). Consider sending reminders "
                "before due dates."
            )
        else:
            risk_level = "high"
            message = (
                f"{facts.late_payment_count} of the last {facts.total} invoices across the portfolio "
                f"were late or overdue (avg {facts.average_days_late} days late). Recommend following "
                "up with affected residents directly."
            )
        if facts.overdue_count:
            message += (
                f" {facts.overdue_count} invoice(s) are currently overdue across the portfolio, "
                f"totaling Rs. {facts.overdue_amount:,.2f}."
            )
        return risk_level, message

    if ratio == 0:
        risk_level = "low"
        message = "Your payments have been consistently on time. Keep it up!"
    elif ratio <= 0.34:
        risk_level = "medium"
        message = (
            f"{facts.late_payment_count} of your last {facts.total} invoices were paid late "
            f"(avg {facts.average_days_late} days). A reminder before the due date could help."
        )
    else:
        risk_level = "high"
        message = (
            f"{facts.late_payment_count} of your last {facts.total} invoices were late or overdue "
            f"(avg {facts.average_days_late} days late). Consider autopay to avoid late fees."
        )

    if facts.overdue_count:
        message += f" You currently have {facts.overdue_count} overdue invoice(s) totaling Rs. {facts.overdue_amount:,.2f}."

    return risk_level, message
